<?php

/**
 * @file
 * Hook implementations for the Blog Author module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function blog_author_entity_base_field_info_alter(array &$fields, EntityTypeInterface $entity_type): void {
  if ($entity_type->id() === 'node' && isset($fields['uid']) && $fields['uid'] instanceof BaseFieldDefinition) {
    $fields['uid']->setDisplayConfigurable('view', TRUE);
  }
}
